services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-app
    container_name: nestjs-app
    # restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: pnpm run start:prod

  mongo:
    image: mongo:7.0
    container_name: mongodb
    # restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_DATABASE: neitec
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
