name: Node.js CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'
        
    - name: Install Dependencies with pnpm
      run: pnpm i --frozen-lockfile

    - name: Build
      run: pnpm run build

  lint:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'
        
    - name: Install Dependencies with pnpm
      run: pnpm i --frozen-lockfile

    - name: Lint
      run: pnpm run lint


  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'
        
    - name: Install Dependencies with pnpm
      run: pnpm i --frozen-lockfile

    - name: Run Tests
      run: pnpm run test
